sudo: false

language: node_js

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "7"
      env: JOB_PART=test
    - os: linux
      node_js: "6"
      env: JOB_PART=test

before_script:
  - npm install bower -g
  - npm install yarn -g

before_install:
  - nvm --version
  - node --version

script:
  - npm run $JOB_PART:travis
